### ISSUE TITLE
Could you add a setup.py for installation?

### ISSUE THREAD

**Issue by jamuwu** [HyperBCS/osu-calc#1]

**Comment by HyperBCS** [comment]
No setup is needed. Once you enter the information in keys.cfg you can run calc.py

**Comment by jamuwu** [comment]
I was thinking more so that it can be run anywhere without needing to be in the directory it's at, just because I'm lazy..

**Comment by Ivoz** [comment]
If anyone would like to attempt this, then 

[sample project](https://github.com/pypa/sampleproject)

exists as an official guide for how a "best practices" fully-installable python project should look like in general.
