### ISSUE TITLE
Write to be python 3 compatible

### ISSUE THREAD

**Issue by Ivoz** [HyperBCS/osu-calc#2]
Either convert to python 3 wholly (it's almost 10 years old now! It's pretty cool! You should try it! It doesn't bite!)

or write to be python 2/3 compatible.

Resources (if you haven't done this before):
* [Porting Python 2 Code to Python 3](https://docs.python.org/3/howto/pyporting.html)
* [2to3 - Automated Python 2 to 3 code translation](https://docs.python.org/3/library/2to3.html)
* [six](https://pythonhosted.org/six/) (simple compatibility library)
* [future](http://python-future.org/) (bigger compatibility library)
* [Porting to Python 3 Redux](http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/)
* [The Updated Guide to Unicode on Python](http://lucumr.pocoo.org/2013/7/2/the-updated-guide-to-unicode/)

**Comment by HyperBCS** [comment]
Sure, I'll give it a try.

**Comment by Ivoz** [comment]
Hey nice! I see you commited 8f6ad7ec915a73983d7e4fd59c6ec088d46450d9

Thanks ^_^

A quick note on github integration:

If in a [hypothetical] commit message, you happen to write somewhere in the message `fixes #2` or `closes #2` (you can see in the url for this issue that it's #2) then when you push that commit into github it will parse that automatically and automatically close this issue noting that the commit "fixed" it.

**Comment by HyperBCS** [comment]
Thanks for the tip! I'm still pretty new to this so every comment helps.
